CXX = g++
CXXFLAGS = -O3 -fPIC -w -I. -DLSB_FIRST -include InfoNES.h -include InfoNES_System.h -include InfoNES_Mapper.h -include K6502.h

SRCS = InfoNES.cpp \
       InfoNES_Mapper.cpp \
       InfoNES_pAPU.cpp \
       K6502.cpp \
       linux/game_input.cpp \
       nano_adapter.cpp

OBJS = $(SRCS:.cpp=.o)

TARGET = nes.so

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) -shared -o $@ $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)